"""One-shot script: append Cerebras BFS panel + BX/BLK/QCOM to source-review queue.

Inputs are the user's BFS analysis (Cerebras D1-D3) plus three earlier
recommendations (BX / BLK / QCOM). Each row is appended only if its primary
ticker is not already in `ai_infra/reports/source_verification_queue_v1.csv`.

Methodology guardrails honoured:
- Every new row enters at `verification_status = pending_original_source_verification`.
- `score_bucket` is `radar_review` (default) or `core_review` for D1 A-rated names.
- `current_pool` starts at `雷达池` / `候选池` based on BFS depth and evidence rating.
- This script never touches `global_universe_v2.jsonl`. Universe promotion still
  requires evidence card + source review + operator decision.

Backup `.bak` copy is written before any change.
"""
from __future__ import annotations

import argparse
import csv
import shutil
import sys
from pathlib import Path

STACK_ROOT = Path(__file__).resolve().parents[1]
QUEUE = STACK_ROOT / "ai_infra" / "reports" / "source_verification_queue_v1.csv"

FIELDS = (
    "rank",
    "priority_tier",
    "ticker",
    "company",
    "market_country",
    "asset_pool",
    "bfs_depth",
    "module",
    "current_pool",
    "total_score",
    "score_bucket",
    "verification_status",
    "source_priority",
    "primary_sources_to_find",
    "metrics_to_verify",
    "upgrade_conditions",
    "downgrade_conditions",
    "evidence_state",
    "counterevidence",
    "dependency_path",
    "dependency_edge",
    "etf_clue",
    "smart_money_clue",
)

# Common templates by module type — keep prose terse and aligned to the
# source-evidence-template anchors.
TPL_SOURCE_PRIORITY = "Find latest annual report, latest quarterly results, earnings call transcript, investor presentation, and official product/capacity pages first."
TPL_PRIMARY_SOURCES_EQUIPMENT = "annual report / quarterly results / earnings call / investor presentation / product roadmap"
TPL_PRIMARY_SOURCES_FINANCE = "10-K/20-F / quarterly results / earnings call / investor day / AUM disclosures"
TPL_VERIFICATION_DEFAULT = "pending_original_source_verification"


# Format: dict per ticker. Required fields:
#   priority_tier, market_country, asset_pool, bfs_depth, module,
#   current_pool, total_score, score_bucket, dependency_path, dependency_edge,
#   evidence_state, counterevidence, primary_sources_to_find, metrics_to_verify,
#   upgrade_conditions, downgrade_conditions, etf_clue, smart_money_clue.
CANDIDATES: list[dict[str, str]] = [
    # ── Earlier user-approved BX / BLK / QCOM ─────────────────────────────
    {
        "ticker": "BX", "company": "Blackstone",
        "priority_tier": "P3_deep_radar",
        "market_country": "US", "asset_pool": "美国资产池",
        "bfs_depth": "D4", "module": "AI data center credit / real estate / infra financing",
        "current_pool": "雷达池", "total_score": "70", "score_bucket": "radar_review",
        "dependency_path": "AI capex demand → data center / REIT financing → Blackstone funds",
        "dependency_edge": "现金流边+资本边",
        "evidence_state": "待原文核验: 数据中心/AI 投资敞口 + private credit AI exposure",
        "counterevidence": "传统房地产/PE 周期、利率敏感、估值贴现",
        "primary_sources_to_find": TPL_PRIMARY_SOURCES_FINANCE,
        "metrics_to_verify": "AI data center exposure ($), private credit AI book, fee-related earnings growth",
        "upgrade_conditions": "Filings disclose explicit AI/data-center fund sizes, fee yields, deployment pace.",
        "downgrade_conditions": "Rates rise, distressed credit migrations, slowing fundraising.",
        "etf_clue": "XLF / private markets ETFs",
        "smart_money_clue": "13F / fund flows",
    },
    {
        "ticker": "BLK", "company": "BlackRock",
        "priority_tier": "P3_deep_radar",
        "market_country": "US", "asset_pool": "美国资产池",
        "bfs_depth": "D5", "module": "Macro capital allocation / infra ETFs / power-grid funds",
        "current_pool": "雷达池", "total_score": "65", "score_bucket": "radar_review",
        "dependency_path": "Global AI buildout → infra/energy capital allocation → BlackRock AUM",
        "dependency_edge": "资本边",
        "evidence_state": "待原文核验: AI/infra fund flows, GIP integration revenue",
        "counterevidence": "passive fee compression, AUM beta dominates",
        "primary_sources_to_find": TPL_PRIMARY_SOURCES_FINANCE,
        "metrics_to_verify": "Infrastructure AUM, AI-themed ETF flows, GIP earnings",
        "upgrade_conditions": "Filings show direct AI-infra fund / private-markets revenue lift.",
        "downgrade_conditions": "Equity beta drawdown, fee compression accelerates.",
        "etf_clue": "BLK is itself in XLF; infra ETFs e.g. PAVE",
        "smart_money_clue": "ETF flow / 13F",
    },
    {
        "ticker": "QCOM", "company": "Qualcomm",
        "priority_tier": "P2_radar_if_blocks_d2",
        "market_country": "US", "asset_pool": "美国资产池",
        "bfs_depth": "D3-D4", "module": "Edge AI / mobile / auto / connectivity silicon",
        "current_pool": "雷达池", "total_score": "75", "score_bucket": "radar_review",
        "dependency_path": "Edge inference + connectivity → mobile/auto/IoT AI silicon",
        "dependency_edge": "客户边+技术边",
        "evidence_state": "待原文核验: edge AI revenue mix, auto/IoT growth, AI 100 Ultra traction",
        "counterevidence": "smartphone cycle, Apple modem in-housing, ASIC替代 in edge",
        "primary_sources_to_find": TPL_PRIMARY_SOURCES_EQUIPMENT,
        "metrics_to_verify": "Auto segment revenue, AI PC chip wins, datacenter inference traction",
        "upgrade_conditions": "Filings disclose AI-accelerator revenue / datacenter qualifications.",
        "downgrade_conditions": "Apple modem in-house, Snapdragon datacenter delayed.",
        "etf_clue": "SMH / SOXX / AIQ",
        "smart_money_clue": "13F large-cap semis",
    },

    # ── Cerebras BFS D=1 (direct nodes, A rating) ─────────────────────────
    {
        "ticker": "CBRS", "company": "Cerebras Systems",
        "priority_tier": "P0_first_batch",
        "market_country": "US", "asset_pool": "美国资产池",
        "bfs_depth": "D1", "module": "Wafer-scale AI accelerator (WSE-3)",
        "current_pool": "核心候选", "total_score": "95", "score_bucket": "core_review",
        "dependency_path": "LLM training/inference → wafer-scale compute → WSE-3 + MemoryX system",
        "dependency_edge": "客户边+技术边+BOM边",
        "evidence_state": "待原文核验: S-1/10-K customer concentration, AWS partner revenue split, TSMC wafer allocation",
        "counterevidence": "IPO 估值、客户集中、TSMC supply 无 long-term commitment、wafer-scale 良率",
        "primary_sources_to_find": "S-1 / 10-K / IPO prospectus / quarterly results / customer announcements (AWS, G42)",
        "metrics_to_verify": "Revenue concentration, wafer cost, MemoryX attach, datacenter capacity",
        "upgrade_conditions": "Direct customer disclosures + S-1 backlog visibility prove durable demand.",
        "downgrade_conditions": "TSMC allocation cap, AWS partnership churn, lockup expiry waves.",
        "etf_clue": "AIQ / IPO ETFs",
        "smart_money_clue": "IPO 13F / lockup tracking",
    },
    {
        "ticker": "DELL", "company": "Dell Technologies",
        "priority_tier": "P0_first_batch",
        "market_country": "US", "asset_pool": "美国资产池",
        "bfs_depth": "D2", "module": "AI server channel / Cerebras-Dell systems / EPYC PowerEdge",
        "current_pool": "核心候选", "total_score": "88", "score_bucket": "core_review",
        "dependency_path": "AI cluster demand → AI server OEM channel → Dell PowerEdge + Cerebras systems",
        "dependency_edge": "客户边+BOM边+渠道边",
        "evidence_state": "待原文核验: ISG AI server revenue mix, Cerebras-Dell joint solution traction, backlog conversion",
        "counterevidence": "GPU pass-through 毛利低、客户集中 hyperscaler、ASP 压力",
        "primary_sources_to_find": TPL_PRIMARY_SOURCES_EQUIPMENT,
        "metrics_to_verify": "AI server revenue, ISG margin, Cerebras solution wins, backlog",
        "upgrade_conditions": "Filings break out AI server / Cerebras-related revenue with margin uplift.",
        "downgrade_conditions": "Hyperscaler in-housing, OEM commoditisation, inventory glut.",
        "etf_clue": "XLK / VGT / AIQ",
        "smart_money_clue": "13F AI hardware",
    },
    {
        "ticker": "BTBT", "company": "Bit Digital",
        "priority_tier": "P1_d1_d3_followup",
        "market_country": "US", "asset_pool": "美国资产池",
        "bfs_depth": "D2", "module": "Inference data center colo (Enovum Montreal CS-3 host)",
        "current_pool": "候选池", "total_score": "78", "score_bucket": "core_review",
        "dependency_path": "AI inference capacity → Enovum colo → CS-3 deployments",
        "dependency_edge": "客户边+产能边+现金流边",
        "evidence_state": "待原文核验: Enovum MW contracted, CS-3 customer, lease length, gross margin",
        "counterevidence": "small-cap balance sheet, BTC mining residual revenue, contract concentration",
        "primary_sources_to_find": "10-K / 10-Q / Enovum press releases / data center contract filings",
        "metrics_to_verify": "Enovum contracted MW, AI revenue %, customer concentration, capex per MW",
        "upgrade_conditions": "Filings disclose multi-year HPC contract size and utilisation.",
        "downgrade_conditions": "Mining cycle drags margins, Enovum churn, capex outruns funding.",
        "etf_clue": "small-cap crypto/AI ETFs",
        "smart_money_clue": "active small-cap funds",
    },
    {
        "ticker": "SNPS", "company": "Synopsys",
        "priority_tier": "P1_d1_d3_followup",
        "market_country": "US", "asset_pool": "美国资产池",
        "bfs_depth": "D3", "module": "EDA + IP (DesignWare sensors used in WSE-2)",
        "current_pool": "候选池", "total_score": "82", "score_bucket": "core_review",
        "dependency_path": "Advanced chip design (incl. wafer-scale) → EDA + IP licensing → Synopsys",
        "dependency_edge": "技术边+客户边",
        "evidence_state": "原文已证明 (DesignWare in-chip monitors on WSE-2); 待核验 WSE-3 收入连续性",
        "counterevidence": "EDA 长周期、Ansys 并购整合、客户集中",
        "primary_sources_to_find": "10-K / earnings call / EDA Tech Symposium / customer references",
        "metrics_to_verify": "Recurring license revenue, IP attach (HBM / die-to-die / monitors), backlog",
        "upgrade_conditions": "WSE-3 / advanced packaging IP wins disclosed; Ansys earnings accretion.",
        "downgrade_conditions": "Customer consolidation, Ansys synergy delays, China revenue risk.",
        "etf_clue": "SMH adjacent / IGV",
        "smart_money_clue": "large-cap quality 13F",
    },

    # ── BFS D=2.1 TSMC wafer chain (B rating) ─────────────────────────────
    {
        "ticker": "AMAT", "company": "Applied Materials",
        "priority_tier": "P2_radar_if_blocks_d2",
        "market_country": "US", "asset_pool": "美国资产池",
        "bfs_depth": "D3", "module": "WFE / deposition / materials engineering",
        "current_pool": "雷达池", "total_score": "78", "score_bucket": "radar_review",
        "dependency_path": "Leading-edge capacity → WFE deposition/CMP → AMAT bookings",
        "dependency_edge": "产能边+技术边",
        "evidence_state": "待原文核验: AI/HPC mix, ICAPS vs leading-edge split, services attach",
        "counterevidence": "中国出口管制、ICAPS 周期、客户集中",
        "primary_sources_to_find": TPL_PRIMARY_SOURCES_EQUIPMENT,
        "metrics_to_verify": "Leading-edge bookings, services growth, AGS attach, gross margin",
        "upgrade_conditions": "Disclosures tie new bookings to advanced-node AI capacity.",
        "downgrade_conditions": "Geopolitical tightening, ICAPS rolling over.",
        "etf_clue": "SMH / SOXX",
        "smart_money_clue": "large-cap semi cap 13F",
    },
    {
        "ticker": "LRCX", "company": "Lam Research",
        "priority_tier": "P2_radar_if_blocks_d2",
        "market_country": "US", "asset_pool": "美国资产池",
        "bfs_depth": "D3", "module": "Etch / deposition WFE",
        "current_pool": "雷达池", "total_score": "76", "score_bucket": "radar_review",
        "dependency_path": "HBM / advanced packaging / leading-edge → etch + deposition → LRCX",
        "dependency_edge": "产能边+技术边",
        "evidence_state": "待原文核验: HBM tool mix, China revenue, services growth",
        "counterevidence": "中国占比、NAND 周期、客户集中",
        "primary_sources_to_find": TPL_PRIMARY_SOURCES_EQUIPMENT,
        "metrics_to_verify": "HBM/advanced packaging revenue, China mix, gross margin",
        "upgrade_conditions": "HBM tool growth disclosed; non-China leading-edge bookings expand.",
        "downgrade_conditions": "China restrictions widen, NAND cycle drags.",
        "etf_clue": "SMH / SOXX",
        "smart_money_clue": "13F semis",
    },
    {
        "ticker": "KLAC", "company": "KLA Corporation",
        "priority_tier": "P2_radar_if_blocks_d2",
        "market_country": "US", "asset_pool": "美国资产池",
        "bfs_depth": "D3", "module": "Wafer inspection / metrology / process control",
        "current_pool": "雷达池", "total_score": "78", "score_bucket": "radar_review",
        "dependency_path": "Wafer-scale / advanced packaging yield → inspection/metrology → KLAC",
        "dependency_edge": "产能边+技术边",
        "evidence_state": "待原文核验: advanced packaging inspection growth, HBM/CoWoS process control",
        "counterevidence": "客户集中 TSMC、China exposure、process node 延迟",
        "primary_sources_to_find": TPL_PRIMARY_SOURCES_EQUIPMENT,
        "metrics_to_verify": "Advanced packaging revenue, process control share, services attach",
        "upgrade_conditions": "Wafer-scale yield narrative drives inspection capex.",
        "downgrade_conditions": "Leading-edge delays, China limits, service-attach pause.",
        "etf_clue": "SMH / SOXX",
        "smart_money_clue": "13F quality semis",
    },
    {
        "ticker": "8035.T / TOELY", "company": "Tokyo Electron",
        "priority_tier": "P2_radar_if_blocks_d2",
        "market_country": "日本", "asset_pool": "卫星资产池",
        "bfs_depth": "D3", "module": "Front-end WFE (etch / deposition / coating)",
        "current_pool": "雷达池", "total_score": "74", "score_bucket": "radar_review",
        "dependency_path": "TSMC/Samsung leading-edge capex → front-end WFE → TEL",
        "dependency_edge": "产能边+技术边",
        "evidence_state": "待原文核验: AI / HBM tool mix",
        "counterevidence": "China exposure, NAND cycle, yen volatility",
        "primary_sources_to_find": TPL_PRIMARY_SOURCES_EQUIPMENT,
        "metrics_to_verify": "Tool bookings, HBM mix, services revenue",
        "upgrade_conditions": "Filings tie booking growth to AI capacity adds.",
        "downgrade_conditions": "Memory cycle drag, China revenue compresses.",
        "etf_clue": "Japan semi / SMH",
        "smart_money_clue": "Japan funds / IBKR JP",
    },
    {
        "ticker": "CDNS", "company": "Cadence Design Systems",
        "priority_tier": "P2_radar_if_blocks_d2",
        "market_country": "US", "asset_pool": "美国资产池",
        "bfs_depth": "D3", "module": "EDA + IP (Cerebras direct evidence pending)",
        "current_pool": "雷达池", "total_score": "75", "score_bucket": "radar_review",
        "dependency_path": "Complex chip design → EDA + IP → Cadence subscriptions",
        "dependency_edge": "技术边",
        "evidence_state": "待原文核验: AI / HPC IP attach, Cerebras direct relationship",
        "counterevidence": "subscription beta, competition with Synopsys/Siemens EDA",
        "primary_sources_to_find": "10-K / earnings call / CadenceLIVE keynotes",
        "metrics_to_verify": "IP revenue growth, AI HPC design wins",
        "upgrade_conditions": "Filings disclose wafer-scale or HBM design IP traction.",
        "downgrade_conditions": "Subscription churn, China revenue squeeze.",
        "etf_clue": "IGV / SMH adjacent",
        "smart_money_clue": "quality growth 13F",
    },
    {
        "ticker": "SIE.DE", "company": "Siemens",
        "priority_tier": "P3_deep_radar",
        "market_country": "欧洲", "asset_pool": "卫星资产池",
        "bfs_depth": "D4", "module": "Siemens EDA + industrial automation",
        "current_pool": "雷达池", "total_score": "60", "score_bucket": "radar_review",
        "dependency_path": "EDA + industrial AI/automation → Siemens EDA + DI segments",
        "dependency_edge": "技术边",
        "evidence_state": "待原文核验: EDA AI exposure, AI factory automation revenue",
        "counterevidence": "industrial cycle, broad conglomerate, slow disclosures",
        "primary_sources_to_find": "Annual report / capital markets day / Siemens EDA briefings",
        "metrics_to_verify": "DI EDA revenue, AI factory wins, services attach",
        "upgrade_conditions": "EDA segment grows on AI design wins.",
        "downgrade_conditions": "Industrial weakness, FX drag.",
        "etf_clue": "Europe industrial ETFs",
        "smart_money_clue": "European institutional flows",
    },

    # ── BFS D=2.2 Memory/server (B-/C+) ───────────────────────────────────
    {
        "ticker": "005930.KS", "company": "Samsung Electronics",
        "priority_tier": "P2_radar_if_blocks_d2",
        "market_country": "韩国", "asset_pool": "卫星资产池",
        "bfs_depth": "D2", "module": "Server DRAM / HBM / NAND / foundry",
        "current_pool": "雷达池", "total_score": "76", "score_bucket": "radar_review",
        "dependency_path": "AI compute → HBM / DRAM / NAND demand → Samsung memory",
        "dependency_edge": "BOM边+产能边",
        "evidence_state": "待原文核验: HBM3E qualifications at NVDA/AMD, foundry node yield",
        "counterevidence": "HBM 落后 SK hynix、foundry 良率、汇率",
        "primary_sources_to_find": "Annual report / quarterly results / earnings call / HBM roadmap",
        "metrics_to_verify": "HBM revenue/mix, ASP/bit, foundry leading-edge utilisation",
        "upgrade_conditions": "HBM3E qualification at hyperscalers; foundry yield improves.",
        "downgrade_conditions": "HBM延后、foundry 大客户流失、NAND 价格压力。",
        "etf_clue": "Korea / semi ETFs",
        "smart_money_clue": "Korea ADR / IBKR KR",
    },
    {
        "ticker": "SNDK", "company": "Sandisk",
        "priority_tier": "P3_deep_radar",
        "market_country": "US", "asset_pool": "美国资产池",
        "bfs_depth": "D3", "module": "Enterprise NAND / eSSD supplier",
        "current_pool": "雷达池", "total_score": "62", "score_bucket": "radar_review",
        "dependency_path": "AI server storage attach → enterprise NAND/SSD → Sandisk",
        "dependency_edge": "BOM边",
        "evidence_state": "待原文核验: eSSD mix, hyperscaler qualifications",
        "counterevidence": "NAND 周期、QLC 转换风险、客户集中",
        "primary_sources_to_find": "10-K / 10-Q / earnings call / eSSD roadmap",
        "metrics_to_verify": "eSSD revenue, QLC mix, gross margin",
        "upgrade_conditions": "AI eSSD ramp visible in earnings, ASP rises.",
        "downgrade_conditions": "NAND oversupply, customer concentration drops orders.",
        "etf_clue": "SMH / storage adjacent",
        "smart_money_clue": "storage 13F",
    },

    # ── BFS D=2.3 AWS networking / optics (C+) ────────────────────────────
    {
        "ticker": "FN", "company": "Fabrinet",
        "priority_tier": "P3_deep_radar",
        "market_country": "US", "asset_pool": "美国资产池",
        "bfs_depth": "D2-D3", "module": "Optical / EMS for transceivers and modules",
        "current_pool": "雷达池", "total_score": "70", "score_bucket": "radar_review",
        "dependency_path": "AI datacenter optics → optical EMS manufacturing → Fabrinet",
        "dependency_edge": "BOM边+产能边",
        "evidence_state": "待原文核验: NVDA datacom mix, 800G/1.6T volume share",
        "counterevidence": "customer concentration NVDA, optical price war",
        "primary_sources_to_find": "10-K / 10-Q / earnings call / customer references",
        "metrics_to_verify": "Datacom revenue mix, 800G/1.6T volume, gross margin",
        "upgrade_conditions": "NVDA datacom backlog grows; new optical customers added.",
        "downgrade_conditions": "Optical ASP declines, NVDA share shift to CPO insourcing.",
        "etf_clue": "AIQ / SMH adjacent",
        "smart_money_clue": "13F small-cap AI",
    },

    # ── BFS D=2.4 DC power / cooling (B-/C+) ──────────────────────────────
    {
        "ticker": "SU.PA", "company": "Schneider Electric",
        "priority_tier": "P2_radar_if_blocks_d2",
        "market_country": "欧洲", "asset_pool": "卫星资产池",
        "bfs_depth": "D2-D4", "module": "Data center electrical equipment / UPS / cooling",
        "current_pool": "雷达池", "total_score": "72", "score_bucket": "radar_review",
        "dependency_path": "AI data center buildout → power distribution + cooling → Schneider",
        "dependency_edge": "客户边+产能边",
        "evidence_state": "待原文核验: data center revenue, backlog by region, AI capacity attach",
        "counterevidence": "传统 industrial cycle, FX, EV slowdown",
        "primary_sources_to_find": "Annual report / quarterly results / data center segment briefings",
        "metrics_to_verify": "DC revenue mix, backlog/book-to-bill, gross margin",
        "upgrade_conditions": "Data center revenue and orders accelerate in disclosures.",
        "downgrade_conditions": "Industrial drag, data center pricing pressure.",
        "etf_clue": "Europe industrial / PAVE",
        "smart_money_clue": "European institutional flows",
    },
    {
        "ticker": "MOD", "company": "Modine Manufacturing",
        "priority_tier": "P2_radar_if_blocks_d2",
        "market_country": "US", "asset_pool": "美国资产池",
        "bfs_depth": "D2-D3", "module": "Data center thermal / heat exchangers / coolant distribution",
        "current_pool": "候选池", "total_score": "78", "score_bucket": "radar_review",
        "dependency_path": "AI rack kW rises → liquid cooling / CDU / thermal → Modine",
        "dependency_edge": "客户边+产能边",
        "evidence_state": "待原文核验: data center segment growth, customer concentration",
        "counterevidence": "HVAC cycle, customer concentration, ASP",
        "primary_sources_to_find": TPL_PRIMARY_SOURCES_EQUIPMENT,
        "metrics_to_verify": "Climate Solutions data center revenue, backlog, margin",
        "upgrade_conditions": "Disclosed data center revenue >25% and growing.",
        "downgrade_conditions": "HVAC slowdown, project deferrals.",
        "etf_clue": "PAVE / industrial",
        "smart_money_clue": "small-cap industrial 13F",
    },

    # ── BFS D=3.1 wafer upstream (C+) ─────────────────────────────────────
    {
        "ticker": "4063.T", "company": "Shin-Etsu Chemical",
        "priority_tier": "P3_deep_radar",
        "market_country": "日本", "asset_pool": "卫星资产池",
        "bfs_depth": "D4", "module": "Silicon wafers / photoresist",
        "current_pool": "雷达池", "total_score": "60", "score_bucket": "radar_review",
        "dependency_path": "TSMC leading-edge → 300mm wafers + photoresist → Shin-Etsu",
        "dependency_edge": "BOM边+产能边",
        "evidence_state": "待原文核验: leading-edge wafer share, EUV resist traction",
        "counterevidence": "PVC/chemicals cycle, FX, customer concentration",
        "primary_sources_to_find": "Annual report / quarterly results / capital markets briefing",
        "metrics_to_verify": "Silicon wafer revenue, EUV resist share, gross margin",
        "upgrade_conditions": "EUV resist share gains in disclosures.",
        "downgrade_conditions": "PVC drag, FX hit.",
        "etf_clue": "Japan / SMH",
        "smart_money_clue": "Japan funds / IBKR JP",
    },
    {
        "ticker": "3436.T", "company": "SUMCO",
        "priority_tier": "P3_deep_radar",
        "market_country": "日本", "asset_pool": "卫星资产池",
        "bfs_depth": "D4", "module": "300mm silicon wafers",
        "current_pool": "雷达池", "total_score": "55", "score_bucket": "radar_review",
        "dependency_path": "Leading-edge logic + memory → 300mm wafers → SUMCO",
        "dependency_edge": "BOM边+产能边",
        "evidence_state": "待原文核验: utilisation, long-term agreements",
        "counterevidence": "wafer oversupply, memory cycle",
        "primary_sources_to_find": "Annual report / earnings call / capacity briefing",
        "metrics_to_verify": "Utilisation, LTA pricing, capex pace",
        "upgrade_conditions": "Utilisation recovers; LTA renewals favourable.",
        "downgrade_conditions": "Wafer oversupply, ASP drops.",
        "etf_clue": "Japan / SMH",
        "smart_money_clue": "Japan funds",
    },
    {
        "ticker": "6488.TW", "company": "GlobalWafers",
        "priority_tier": "P3_deep_radar",
        "market_country": "台湾", "asset_pool": "卫星资产池",
        "bfs_depth": "D4", "module": "300mm silicon wafers (TW + Siltronic deal history)",
        "current_pool": "雷达池", "total_score": "55", "score_bucket": "radar_review",
        "dependency_path": "Leading-edge fab demand → 300mm wafers → GlobalWafers",
        "dependency_edge": "BOM边+产能边",
        "evidence_state": "待原文核验: LTA disclosures, US capex execution",
        "counterevidence": "wafer oversupply, geopolitical",
        "primary_sources_to_find": "Annual report / capex updates / customer LTAs",
        "metrics_to_verify": "LTA value, utilisation, Texas/Korea capex progress",
        "upgrade_conditions": "LTAs renew higher pricing; US fab ramp on schedule.",
        "downgrade_conditions": "LTAs lapse, capex overruns.",
        "etf_clue": "Taiwan semi",
        "smart_money_clue": "IBKR TW / regional funds",
    },
    {
        "ticker": "WAF.DE", "company": "Siltronic",
        "priority_tier": "P3_deep_radar",
        "market_country": "欧洲", "asset_pool": "卫星资产池",
        "bfs_depth": "D4", "module": "300mm silicon wafers (Europe)",
        "current_pool": "雷达池", "total_score": "50", "score_bucket": "radar_review",
        "dependency_path": "Leading-edge fab demand → 300mm wafers → Siltronic",
        "dependency_edge": "BOM边+产能边",
        "evidence_state": "待原文核验: utilisation, Singapore expansion ramp",
        "counterevidence": "wafer oversupply, smaller scale vs Shin-Etsu/SUMCO",
        "primary_sources_to_find": "Annual report / capacity report",
        "metrics_to_verify": "Utilisation, Singapore ramp, LTAs",
        "upgrade_conditions": "Singapore ramp ahead of schedule.",
        "downgrade_conditions": "Utilisation drops, ASP under pressure.",
        "etf_clue": "Europe semi",
        "smart_money_clue": "European institutional",
    },
    {
        "ticker": "ENTG", "company": "Entegris",
        "priority_tier": "P3_deep_radar",
        "market_country": "US", "asset_pool": "美国资产池",
        "bfs_depth": "D4", "module": "Specialty materials / advanced cleans / filtration",
        "current_pool": "雷达池", "total_score": "58", "score_bucket": "radar_review",
        "dependency_path": "Leading-edge fabs / advanced packaging → specialty materials → Entegris",
        "dependency_edge": "BOM边+技术边",
        "evidence_state": "待原文核验: advanced packaging revenue, China revenue",
        "counterevidence": "China exposure, services attach",
        "primary_sources_to_find": "10-K / quarterly results / capital markets day",
        "metrics_to_verify": "Advanced node revenue, China mix, gross margin",
        "upgrade_conditions": "Advanced node specialty revenue accelerates.",
        "downgrade_conditions": "China revenue compresses, FX.",
        "etf_clue": "SMH / SOXX",
        "smart_money_clue": "specialty chemicals 13F",
    },
    {
        "ticker": "MRK.DE", "company": "Merck KGaA",
        "priority_tier": "P3_deep_radar",
        "market_country": "欧洲", "asset_pool": "卫星资产池",
        "bfs_depth": "D4", "module": "Electronic materials / specialty chemicals",
        "current_pool": "雷达池", "total_score": "52", "score_bucket": "radar_review",
        "dependency_path": "Leading-edge fabs → electronic materials → Merck KGaA",
        "dependency_edge": "BOM边",
        "evidence_state": "待原文核验: Electronics segment AI revenue mix",
        "counterevidence": "pharma drag, diversified conglomerate",
        "primary_sources_to_find": "Annual report / Electronics segment briefing",
        "metrics_to_verify": "Electronics revenue, advanced materials growth",
        "upgrade_conditions": "Electronics segment doubles AI exposure.",
        "downgrade_conditions": "Pharma deteriorates, FX.",
        "etf_clue": "Europe specialty chemicals",
        "smart_money_clue": "European institutional",
    },
    {
        "ticker": "4186.T", "company": "Tokyo Ohka Kogyo",
        "priority_tier": "P3_deep_radar",
        "market_country": "日本", "asset_pool": "卫星资产池",
        "bfs_depth": "D4", "module": "Photoresist / specialty chemicals for advanced nodes",
        "current_pool": "雷达池", "total_score": "55", "score_bucket": "radar_review",
        "dependency_path": "EUV / leading-edge resist → TOK",
        "dependency_edge": "BOM边+技术边",
        "evidence_state": "待原文核验: EUV resist share",
        "counterevidence": "Shin-Etsu/JSR competition, FX",
        "primary_sources_to_find": "Annual report / customer references",
        "metrics_to_verify": "EUV resist share, leading-edge customer mix",
        "upgrade_conditions": "EUV share gains disclosed.",
        "downgrade_conditions": "Customer share loss.",
        "etf_clue": "Japan semi",
        "smart_money_clue": "Japan funds",
    },
    {
        "ticker": "4901.T", "company": "Fujifilm",
        "priority_tier": "P3_deep_radar",
        "market_country": "日本", "asset_pool": "卫星资产池",
        "bfs_depth": "D4", "module": "Electronic materials / imaging / healthcare",
        "current_pool": "雷达池", "total_score": "48", "score_bucket": "radar_review",
        "dependency_path": "Advanced node photolithography materials → Fujifilm Electronics",
        "dependency_edge": "BOM边",
        "evidence_state": "待原文核验: Electronic materials segment mix",
        "counterevidence": "consumer imaging drag, healthcare cycle",
        "primary_sources_to_find": "Annual report / Electronic Materials briefing",
        "metrics_to_verify": "Electronic Materials revenue, AI-related growth",
        "upgrade_conditions": "Electronic Materials AI exposure quantified.",
        "downgrade_conditions": "Imaging/Healthcare drag dominates.",
        "etf_clue": "Japan diversified",
        "smart_money_clue": "Japan funds",
    },
    {
        "ticker": "LIN", "company": "Linde",
        "priority_tier": "P3_deep_radar",
        "market_country": "US", "asset_pool": "美国资产池",
        "bfs_depth": "D4", "module": "Industrial gases for semiconductor fabs",
        "current_pool": "雷达池", "total_score": "55", "score_bucket": "radar_review",
        "dependency_path": "Leading-edge fab gas demand → Linde",
        "dependency_edge": "BOM边",
        "evidence_state": "待原文核验: Electronics gas revenue, AI fab supply contracts",
        "counterevidence": "broad industrial conglomerate; AI单点弹性低",
        "primary_sources_to_find": "10-K / Electronics segment disclosures",
        "metrics_to_verify": "Electronics gas revenue mix, long-term contracts with fabs",
        "upgrade_conditions": "Electronics segment outpaces overall gas growth.",
        "downgrade_conditions": "Industrial cycle drag, contract renewals weaken.",
        "etf_clue": "XLB / specialty industrial",
        "smart_money_clue": "quality industrial 13F",
    },
    {
        "ticker": "AI.PA", "company": "Air Liquide",
        "priority_tier": "P3_deep_radar",
        "market_country": "欧洲", "asset_pool": "卫星资产池",
        "bfs_depth": "D4", "module": "Industrial gases for fabs",
        "current_pool": "雷达池", "total_score": "50", "score_bucket": "radar_review",
        "dependency_path": "Leading-edge fab gas demand → Air Liquide Electronics",
        "dependency_edge": "BOM边",
        "evidence_state": "待原文核验: Electronics gas revenue",
        "counterevidence": "industrial cycle, FX",
        "primary_sources_to_find": "Annual report / Electronics segment",
        "metrics_to_verify": "Electronics gas revenue, contract pipeline",
        "upgrade_conditions": "Electronics segment growth accelerates.",
        "downgrade_conditions": "Industrial drag.",
        "etf_clue": "Europe industrial gases",
        "smart_money_clue": "European institutional",
    },
    {
        "ticker": "4091.T", "company": "Nippon Sanso (Taiyo Nippon Sanso)",
        "priority_tier": "P3_deep_radar",
        "market_country": "日本", "asset_pool": "卫星资产池",
        "bfs_depth": "D4", "module": "Industrial gases including specialty fab gases",
        "current_pool": "雷达池", "total_score": "45", "score_bucket": "radar_review",
        "dependency_path": "Japan/global fab gas demand → Nippon Sanso",
        "dependency_edge": "BOM边",
        "evidence_state": "待原文核验: Electronics segment growth",
        "counterevidence": "FX, diversification drag",
        "primary_sources_to_find": "Annual report / Electronics segment",
        "metrics_to_verify": "Electronics gas revenue, customer concentration",
        "upgrade_conditions": "Electronics segment expands.",
        "downgrade_conditions": "Industrial cycle weakness.",
        "etf_clue": "Japan industrial",
        "smart_money_clue": "Japan funds",
    },
    {
        "ticker": "VACN.SW", "company": "VAT Group",
        "priority_tier": "P3_deep_radar",
        "market_country": "欧洲", "asset_pool": "卫星资产池",
        "bfs_depth": "D4", "module": "High-end vacuum valves for WFE",
        "current_pool": "雷达池", "total_score": "58", "score_bucket": "radar_review",
        "dependency_path": "WFE leading-edge → vacuum valves → VAT Group",
        "dependency_edge": "BOM边+技术边",
        "evidence_state": "待原文核验: leading-edge bookings",
        "counterevidence": "WFE cycle, customer concentration",
        "primary_sources_to_find": "Annual report / quarterly results / customer mix",
        "metrics_to_verify": "WFE bookings, customer split, gross margin",
        "upgrade_conditions": "Leading-edge bookings step up.",
        "downgrade_conditions": "WFE cycle drags.",
        "etf_clue": "Europe semi cap",
        "smart_money_clue": "European institutional",
    },
    {
        "ticker": "7735.T", "company": "Screen Holdings",
        "priority_tier": "P3_deep_radar",
        "market_country": "日本", "asset_pool": "卫星资产池",
        "bfs_depth": "D4", "module": "Wafer cleaning equipment / WFE",
        "current_pool": "雷达池", "total_score": "52", "score_bucket": "radar_review",
        "dependency_path": "Leading-edge fab cleaning → Screen",
        "dependency_edge": "产能边+技术边",
        "evidence_state": "待原文核验: HBM/advanced packaging cleaning revenue",
        "counterevidence": "WFE cycle, FX",
        "primary_sources_to_find": "Annual report / segment results",
        "metrics_to_verify": "SPE revenue, advanced packaging share",
        "upgrade_conditions": "Advanced packaging cleaning revenue accelerates.",
        "downgrade_conditions": "WFE cycle drag.",
        "etf_clue": "Japan semi",
        "smart_money_clue": "Japan funds",
    },
    {
        "ticker": "6525.T", "company": "Kokusai Electric",
        "priority_tier": "P3_deep_radar",
        "market_country": "日本", "asset_pool": "卫星资产池",
        "bfs_depth": "D4", "module": "Batch deposition equipment for HBM / DRAM",
        "current_pool": "雷达池", "total_score": "50", "score_bucket": "radar_review",
        "dependency_path": "HBM / DRAM scaling → batch deposition → Kokusai",
        "dependency_edge": "产能边+技术边",
        "evidence_state": "待原文核验: HBM tool order book",
        "counterevidence": "WFE cycle, China revenue exposure",
        "primary_sources_to_find": "Annual report / earnings call",
        "metrics_to_verify": "HBM bookings, China mix, gross margin",
        "upgrade_conditions": "HBM bookings grow; non-China mix expands.",
        "downgrade_conditions": "HBM scaling delayed.",
        "etf_clue": "Japan semi",
        "smart_money_clue": "Japan funds",
    },

    # ── BFS D=3.2 power semis / cooling (C+) ──────────────────────────────
    {
        "ticker": "STM", "company": "STMicroelectronics",
        "priority_tier": "P3_deep_radar",
        "market_country": "欧洲", "asset_pool": "卫星资产池",
        "bfs_depth": "D3-D4", "module": "Power semiconductors / SiC / industrial",
        "current_pool": "雷达池", "total_score": "55", "score_bucket": "radar_review",
        "dependency_path": "AI data center power conversion + EV → power semis → STM",
        "dependency_edge": "BOM边",
        "evidence_state": "待原文核验: data center power share, SiC growth",
        "counterevidence": "auto cycle, ICAPS pricing",
        "primary_sources_to_find": "Annual report / earnings call / industrial segment",
        "metrics_to_verify": "Power & energy revenue, SiC pipeline, AI share",
        "upgrade_conditions": "Data center power exposure quantified.",
        "downgrade_conditions": "Auto demand drag dominates.",
        "etf_clue": "Europe semi",
        "smart_money_clue": "European institutional",
    },
    {
        "ticker": "NVTS", "company": "Navitas Semiconductor",
        "priority_tier": "P2_radar_if_blocks_d2",
        "market_country": "US", "asset_pool": "美国资产池",
        "bfs_depth": "D3-D4", "module": "GaN power semis / data center power",
        "current_pool": "雷达池", "total_score": "62", "score_bucket": "radar_review",
        "dependency_path": "AI rack power density rises → GaN / SiC power → Navitas",
        "dependency_edge": "BOM边+技术边",
        "evidence_state": "待原文核验: data center revenue traction, hyperscaler design wins",
        "counterevidence": "small-cap balance sheet, GaN adoption pace",
        "primary_sources_to_find": "10-K / quarterly results / hyperscaler PR",
        "metrics_to_verify": "Data center revenue, design wins, gross margin",
        "upgrade_conditions": "Data center revenue accelerates beyond consumer.",
        "downgrade_conditions": "Design-in delays, balance-sheet pressure.",
        "etf_clue": "small-cap semi",
        "smart_money_clue": "small-cap AI funds",
    },
    {
        "ticker": "POWI", "company": "Power Integrations",
        "priority_tier": "P3_deep_radar",
        "market_country": "US", "asset_pool": "美国资产池",
        "bfs_depth": "D3-D4", "module": "AC-DC power conversion ICs",
        "current_pool": "雷达池", "total_score": "55", "score_bucket": "radar_review",
        "dependency_path": "Data center / industrial power conversion → POWI",
        "dependency_edge": "BOM边",
        "evidence_state": "待原文核验: data center / industrial revenue mix",
        "counterevidence": "consumer cycle, communications exposure",
        "primary_sources_to_find": "10-K / quarterly results",
        "metrics_to_verify": "Industrial / DC revenue, gross margin",
        "upgrade_conditions": "DC AI revenue share rises.",
        "downgrade_conditions": "Consumer drag.",
        "etf_clue": "small-cap semi",
        "smart_money_clue": "small-cap quality 13F",
    },
    {
        "ticker": "MPWR", "company": "Monolithic Power Systems",
        "priority_tier": "P2_radar_if_blocks_d2",
        "market_country": "US", "asset_pool": "美国资产池",
        "bfs_depth": "D3", "module": "Server / GPU board power modules",
        "current_pool": "候选池", "total_score": "75", "score_bucket": "radar_review",
        "dependency_path": "GPU / accelerator board power → MPS multi-phase modules",
        "dependency_edge": "BOM边+技术边",
        "evidence_state": "待原文核验: NVDA / hyperscaler design wins, share vs MPS competitor",
        "counterevidence": "competition (Renesas, IDT), customer concentration",
        "primary_sources_to_find": "10-K / earnings call / GPU board teardown reports",
        "metrics_to_verify": "Compute revenue, GPU board share, gross margin",
        "upgrade_conditions": "Filings tie growth to AI compute boards.",
        "downgrade_conditions": "Share loss to competitor; ASP pressure.",
        "etf_clue": "SMH / SOXX",
        "smart_money_clue": "13F quality semis",
    },
    {
        "ticker": "6282.TW", "company": "AcBel Polytech",
        "priority_tier": "P3_deep_radar",
        "market_country": "台湾", "asset_pool": "卫星资产池",
        "bfs_depth": "D3-D4", "module": "Server / data center power supplies",
        "current_pool": "雷达池", "total_score": "50", "score_bucket": "radar_review",
        "dependency_path": "AI server PSU demand → AcBel",
        "dependency_edge": "BOM边",
        "evidence_state": "待原文核验: AI server PSU mix",
        "counterevidence": "consumer PSU cycle, customer concentration",
        "primary_sources_to_find": "Annual report / quarterly results",
        "metrics_to_verify": "DC PSU revenue, gross margin",
        "upgrade_conditions": "AI server PSU share grows.",
        "downgrade_conditions": "Consumer drag.",
        "etf_clue": "Taiwan power",
        "smart_money_clue": "IBKR TW",
    },
    {
        "ticker": "VICR", "company": "Vicor",
        "priority_tier": "P3_deep_radar",
        "market_country": "US", "asset_pool": "美国资产池",
        "bfs_depth": "D3", "module": "High-density power modules for AI compute",
        "current_pool": "雷达池", "total_score": "58", "score_bucket": "radar_review",
        "dependency_path": "AI rack power density → high-density modules → Vicor",
        "dependency_edge": "BOM边+技术边",
        "evidence_state": "待原文核验: hyperscaler design wins, capacity ramp",
        "counterevidence": "small-cap execution, competition with Eaton/Delta",
        "primary_sources_to_find": "10-K / 10-Q / capital markets briefing",
        "metrics_to_verify": "Bookings, customer mix, gross margin",
        "upgrade_conditions": "Bookings accelerate with explicit AI hyperscaler customers.",
        "downgrade_conditions": "Design losses, capacity overruns.",
        "etf_clue": "small-cap industrial",
        "smart_money_clue": "small-cap industrial 13F",
    },
    {
        "ticker": "6594.T", "company": "Nidec",
        "priority_tier": "P3_deep_radar",
        "market_country": "日本", "asset_pool": "卫星资产池",
        "bfs_depth": "D4", "module": "Motors / cooling / industrial automation",
        "current_pool": "雷达池", "total_score": "48", "score_bucket": "radar_review",
        "dependency_path": "Data center cooling fans + EV motors → Nidec",
        "dependency_edge": "BOM边",
        "evidence_state": "待原文核验: data center fan revenue, EV motor cycle",
        "counterevidence": "EV demand cycle, FX",
        "primary_sources_to_find": "Annual report / segment briefings",
        "metrics_to_verify": "DC fan / cooling revenue, EV motor backlog",
        "upgrade_conditions": "Data center cooling revenue accelerates.",
        "downgrade_conditions": "EV slowdown drags overall.",
        "etf_clue": "Japan industrial",
        "smart_money_clue": "Japan funds",
    },
    {
        "ticker": "6367.T", "company": "Daikin Industries",
        "priority_tier": "P3_deep_radar",
        "market_country": "日本", "asset_pool": "卫星资产池",
        "bfs_depth": "D4", "module": "Data center HVAC / chillers",
        "current_pool": "雷达池", "total_score": "46", "score_bucket": "radar_review",
        "dependency_path": "Data center HVAC demand → Daikin",
        "dependency_edge": "BOM边",
        "evidence_state": "待原文核验: data center HVAC mix",
        "counterevidence": "residential HVAC cycle, FX",
        "primary_sources_to_find": "Annual report / segment briefings",
        "metrics_to_verify": "DC HVAC revenue, customer wins",
        "upgrade_conditions": "DC HVAC revenue accelerates above residential.",
        "downgrade_conditions": "Residential drag dominates.",
        "etf_clue": "Japan industrial",
        "smart_money_clue": "Japan funds",
    },
    {
        "ticker": "ETN", "company": "Eaton",
        "priority_tier": "P2_radar_if_blocks_d2",
        "market_country": "US", "asset_pool": "美国资产池",
        "bfs_depth": "D2-D4", "module": "Electrical equipment / power management",
        "current_pool": "候选池", "total_score": "76", "score_bucket": "radar_review",
        "dependency_path": "AI data center buildout → electrical equipment / UPS → Eaton",
        "dependency_edge": "客户边+产能边",
        "evidence_state": "待原文核验: Electrical segment data center revenue",
        "counterevidence": "industrial cycle, project timing",
        "primary_sources_to_find": "10-K / quarterly results / capital markets day",
        "metrics_to_verify": "Electrical Americas revenue, DC backlog, gross margin",
        "upgrade_conditions": "DC backlog hits multi-year highs in disclosures.",
        "downgrade_conditions": "Industrial cycle deteriorates broadly.",
        "etf_clue": "PAVE / XLI",
        "smart_money_clue": "13F industrial",
    },

    # ── BFS D=3.3 inference alt / competitor ──────────────────────────────
    {
        "ticker": "INTC", "company": "Intel",
        "priority_tier": "P3_deep_radar",
        "market_country": "US", "asset_pool": "美国资产池",
        "bfs_depth": "D1-D4", "module": "Gaudi / Xeon / IFS foundry",
        "current_pool": "雷达池", "total_score": "55", "score_bucket": "radar_review",
        "dependency_path": "AI compute alt + foundry → Gaudi accelerator + Xeon + IFS",
        "dependency_edge": "客户边+技术边",
        "evidence_state": "待原文核验: Gaudi revenue, IFS roadmap traction",
        "counterevidence": "execution risk, AMD/NVDA share, foundry capex",
        "primary_sources_to_find": "10-K / quarterly results / IFS roadmap",
        "metrics_to_verify": "Gaudi revenue, IFS bookings, Xeon AI uptake",
        "upgrade_conditions": "Gaudi traction or IFS customer wins disclosed.",
        "downgrade_conditions": "Continued share loss to AMD / TSMC.",
        "etf_clue": "SMH / SOXX",
        "smart_money_clue": "13F semis",
    },
]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--queue", type=Path, default=QUEUE)
    parser.add_argument("--no-backup", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    if not args.queue.exists():
        print(f"error: queue not found at {args.queue}", file=sys.stderr)
        return 2

    with args.queue.open("r", encoding="utf-8") as handle:
        existing_rows = list(csv.DictReader(handle))
    existing_tickers: set[str] = set()
    for row in existing_rows:
        for piece in (row.get("ticker") or "").split("/"):
            t = piece.strip().upper()
            if t:
                existing_tickers.add(t)

    max_rank = max((int(r["rank"]) for r in existing_rows if r.get("rank") and r["rank"].isdigit()), default=0)

    new_rows: list[dict[str, str]] = []
    skipped: list[str] = []
    for candidate in CANDIDATES:
        ticker_field = candidate["ticker"]
        primary = ticker_field.split("/")[0].strip().upper()
        if primary in existing_tickers:
            skipped.append(primary)
            continue
        max_rank += 1
        row = {key: "" for key in FIELDS}
        row.update({
            "rank": str(max_rank),
            "verification_status": TPL_VERIFICATION_DEFAULT,
            "source_priority": TPL_SOURCE_PRIORITY,
        })
        row.update({k: v for k, v in candidate.items() if k in FIELDS})
        new_rows.append(row)
        existing_tickers.add(primary)

    if not new_rows:
        print(f"No new tickers to add; {len(skipped)} already in queue")
        return 0

    if args.dry_run:
        print(f"dry-run: would add {len(new_rows)} rows, skip {len(skipped)} existing")
        for row in new_rows:
            print(f"  + rank={row['rank']} ticker={row['ticker']:20} tier={row['priority_tier']:24} depth={row['bfs_depth']:6} module={row['module']}")
        return 0

    if not args.no_backup:
        shutil.copy2(args.queue, args.queue.with_suffix(args.queue.suffix + ".bak"))
        print(f"backup: {args.queue.with_suffix(args.queue.suffix + '.bak')}")

    with args.queue.open("a", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=FIELDS)
        for row in new_rows:
            writer.writerow(row)
    print(f"Appended {len(new_rows)} new rows; skipped {len(skipped)} existing")
    for row in new_rows:
        print(f"  + #{row['rank']} {row['ticker']:22} {row['priority_tier']:22} {row['bfs_depth']:6} {row['module']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
