"""
Gmail delivery with inline chart images.

Converts markdown report → styled HTML email → sends via Gmail API
with chart PNGs embedded as CID inline attachments.

Usage:
    from quant_bot.delivery.gmail import send_report_email, create_report_draft

    # Send directly
    send_report_email(
        report_md=Path("reports/2026-03-08_report.md"),
        chart_paths=[Path("reports/charts/2026-03-08/sector_performance.png"), ...],
        to="you@example.com",
        subject="Quant Research Report — 2026-03-08",
    )

    # Or create draft
    create_report_draft(
        report_md=Path("reports/2026-03-08_report.md"),
        chart_paths=[...],
        to="you@example.com",
        subject="Quant Research Report — 2026-03-08",
    )
"""
from __future__ import annotations

import base64
import mimetypes
import re
from email.mime.base import MIMEBase
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

import markdown
from premailer import transform

import yaml
import structlog

log = structlog.get_logger()

# ── OAuth constants ──────────────────────────────────────────────────────────
SCOPES = ["https://www.googleapis.com/auth/gmail.compose"]


def load_recipients(config_path: str = "config.yaml") -> list[str]:
    """Load recipient list from config.yaml → reporting.recipients.
    NEVER hallucinate email addresses — always read from config."""
    p = Path(config_path)
    if not p.exists():
        raise FileNotFoundError(f"Config not found: {p}. Cannot determine recipients.")
    cfg = yaml.safe_load(p.read_text())
    recipients = cfg.get("reporting", {}).get("recipients", [])
    if not recipients or recipients == ["you@example.com"]:
        raise ValueError("No recipients configured. Edit config.yaml → reporting.recipients")
    return recipients
TOKEN_PATH = Path("token.json")
CREDENTIALS_PATH = Path("credentials.json")


# ── HTML email template ──────────────────────────────────────────────────────
EMAIL_CSS = """
body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
    line-height: 1.6;
    color: #1a1a2e;
    background-color: #f8f9fa;
    margin: 0;
    padding: 0;
}
.container {
    max-width: 800px;
    margin: 0 auto;
    padding: 24px;
    background: #ffffff;
}
h1 {
    color: #1a1a2e;
    border-bottom: 3px solid #3742fa;
    padding-bottom: 8px;
    font-size: 22px;
}
h2 {
    color: #1a1a2e;
    border-bottom: 1px solid #e0e0e0;
    padding-bottom: 6px;
    margin-top: 28px;
    font-size: 18px;
}
h3 {
    color: #2d3436;
    margin-top: 20px;
    font-size: 15px;
}
table {
    border-collapse: collapse;
    width: 100%;
    margin: 12px 0;
    font-size: 13px;
}
th {
    background-color: #1a1a2e;
    color: #ffffff;
    padding: 8px 10px;
    text-align: left;
    font-weight: 600;
}
td {
    padding: 6px 10px;
    border-bottom: 1px solid #e8e8e8;
}
tr:nth-child(even) {
    background-color: #f5f6fa;
}
blockquote {
    border-left: 4px solid #3742fa;
    margin: 12px 0;
    padding: 8px 16px;
    background: #f0f1ff;
    color: #555;
    font-size: 13px;
}
code {
    background: #f0f1ff;
    padding: 2px 6px;
    border-radius: 3px;
    font-size: 12px;
}
strong {
    color: #1a1a2e;
}
hr {
    border: none;
    border-top: 1px solid #e0e0e0;
    margin: 20px 0;
}
img.chart {
    max-width: 100%;
    height: auto;
    border-radius: 8px;
    margin: 12px 0;
    box-shadow: 0 2px 8px rgba(0,0,0,0.1);
}
.chart-title {
    font-size: 13px;
    color: #636e72;
    margin-bottom: 4px;
    font-weight: 600;
}
.footer {
    margin-top: 32px;
    padding-top: 16px;
    border-top: 1px solid #e0e0e0;
    font-size: 11px;
    color: #b2bec3;
    text-align: center;
}
ul, ol {
    padding-left: 24px;
}
li {
    margin-bottom: 4px;
}
"""

HTML_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>{css}</style>
</head>
<body>
<div class="container">
{body}
<div class="footer">
    Generated by quant-research-v1 &middot; Not financial advice
</div>
</div>
</body>
</html>"""


# ── Markdown → HTML conversion ──────────────────────────────────────────────

CHART_TITLES = {
    "sector_performance": "Sector Performance",
    "notable_items": "Top Notable Items",
    "cross_asset": "Cross-Asset Dashboard",
    "dyp_candidates": "Dividend Yield Dip Candidates",
    "index_trends": "Major Index Trends (60D)",
    "vix_trend": "VIX — Market Fear Gauge",
    "top_movers": "Top Movers — Winners & Losers",
}

# Map chart stems to the h2 heading they should appear AFTER.
# Charts are inserted after the first <h2> whose text contains the keyword.
# If no match, the chart goes to a fallback section at the end.
CHART_SECTION_MAP = {
    "sector_performance": "Market Context",
    "index_trends": "Market Context",
    "vix_trend": "Market Context",
    "notable_items": "HIGH CONFIDENCE",
    "top_movers": "MODERATE",
    "cross_asset": "Cross-Asset",
    "dyp_candidates": "Dividend",
}


def _chart_img_html(cid: str, title: str) -> str:
    """Build inline chart HTML block."""
    return (
        f'<p style="font-size:13px;color:#636e72;font-weight:600;'
        f'margin-bottom:4px;margin-top:16px">{title}</p>\n'
        f'<img src="cid:{cid}" alt="{title}" '
        f'style="max-width:100%;height:auto;border-radius:8px;'
        f'margin:0 0 20px 0;box-shadow:0 2px 8px rgba(0,0,0,0.1)">\n'
    )


def _insert_charts_after_sections(
    html_body: str,
    chart_paths: list[Path],
    chart_cid_map: dict[str, str],
) -> str:
    """
    Insert chart images after their matching report sections.
    Charts are placed after the LAST element before the next <h2>,
    i.e. at the end of the section they belong to.
    Unmatched charts go to a fallback section at the bottom.
    """
    if not chart_paths or not chart_cid_map:
        return html_body

    # Build insertion map: section_keyword → list of chart HTML snippets
    section_charts: dict[str, list[str]] = {}
    unmatched: list[str] = []

    for cp in chart_paths:
        cid = chart_cid_map.get(str(cp))
        if not cid:
            continue
        stem = Path(cp).stem
        title = CHART_TITLES.get(stem, stem.replace("_", " ").title())
        img_html = _chart_img_html(cid, title)

        keyword = CHART_SECTION_MAP.get(stem)
        if keyword:
            section_charts.setdefault(keyword, []).append(img_html)
        else:
            unmatched.append(img_html)

    # Find all <h2> positions to determine section boundaries
    h2_pattern = re.compile(r'<h2[^>]*>(.*?)</h2>', re.IGNORECASE | re.DOTALL)
    h2_matches = list(h2_pattern.finditer(html_body))

    if not h2_matches:
        # No sections found — append everything at the end
        for charts in section_charts.values():
            html_body += "".join(charts)
        html_body += "".join(unmatched)
        return html_body

    # For each section keyword, find where it matches and insert charts
    # Work backwards so insertion positions stay valid
    insertions: list[tuple[int, str]] = []  # (position, html_to_insert)

    for keyword, charts_html_list in section_charts.items():
        # Find the h2 that contains this keyword
        matched_idx = None
        for i, m in enumerate(h2_matches):
            if keyword.lower() in m.group(1).lower():
                matched_idx = i
                break

        if matched_idx is None:
            unmatched.extend(charts_html_list)
            continue

        # Insert position = start of next <h2>, or end of body
        if matched_idx + 1 < len(h2_matches):
            # Find the <hr> or whitespace just before the next h2
            next_h2_start = h2_matches[matched_idx + 1].start()
            # Look for preceding <hr> tag to insert before it
            preceding = html_body[max(0, next_h2_start - 80):next_h2_start]
            hr_pos = preceding.rfind('<hr')
            if hr_pos >= 0:
                insert_pos = max(0, next_h2_start - 80) + hr_pos
            else:
                insert_pos = next_h2_start
        else:
            insert_pos = len(html_body)

        insertions.append((insert_pos, "".join(charts_html_list)))

    # Sort insertions by position descending so we don't shift indices
    insertions.sort(key=lambda x: x[0], reverse=True)
    for pos, html_snippet in insertions:
        html_body = html_body[:pos] + html_snippet + html_body[pos:]

    # Append any unmatched charts at the end
    if unmatched:
        html_body += "".join(unmatched)

    return html_body


def _md_to_html(
    md_text: str,
    chart_cid_map: dict[str, str],
    chart_paths: list[Path],
) -> str:
    """
    Convert markdown to styled HTML email.

    1. Replace any ![title](path) in the markdown with CID images.
    2. Insert remaining charts inline after their matching report sections.
    3. Any unmatched charts go to the bottom.
    """
    # Replace markdown image refs if present
    already_placed = set()

    def _replace_image(match):
        alt = match.group(1)
        img_path = match.group(2)
        for path_str, cid in chart_cid_map.items():
            if Path(img_path).name == Path(path_str).name:
                already_placed.add(path_str)
                return (
                    f'<p class="chart-title">{alt}</p>\n'
                    f'<img src="cid:{cid}" alt="{alt}" class="chart"'
                    f' style="max-width:100%;height:auto;border-radius:8px;'
                    f'margin:12px 0;box-shadow:0 2px 8px rgba(0,0,0,0.1)">'
                )
        return f"*[Chart: {alt}]*"

    md_text = re.sub(r'!\[([^\]]*)\]\(([^)]+)\)', _replace_image, md_text)

    # Convert markdown to HTML
    html_body = markdown.markdown(
        md_text,
        extensions=["tables", "fenced_code"],
    )

    # Insert charts that weren't already placed via markdown refs
    remaining = [cp for cp in chart_paths if str(cp) not in already_placed]
    html_body = _insert_charts_after_sections(html_body, remaining, chart_cid_map)

    # Wrap in template with inline styles
    full_html = HTML_TEMPLATE.format(css=EMAIL_CSS, body=html_body)

    # Inline CSS for email client compatibility
    try:
        full_html = transform(full_html, remove_classes=False)
    except Exception as e:
        log.warning("premailer_failed", error=str(e))

    return full_html


# ── MIME message building ────────────────────────────────────────────────────

def build_email_message(
    to: str,
    subject: str,
    html: str,
    chart_paths: list[Path],
    chart_cid_map: dict[str, str],
    sender: str = "me",
    bcc: list[str] | None = None,
) -> MIMEMultipart:
    """Build a multipart/related MIME message with inline chart images.

    Uses the RFC 2387 structure Gmail expects:
        multipart/related
        ├── multipart/alternative
        │   ├── text/plain (fallback)
        │   └── text/html  (with cid: refs)
        ├── image/png (Content-ID)
        └── ...
    """
    msg = MIMEMultipart("related")
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = to
    if bcc:
        msg["Bcc"] = ", ".join(bcc)

    # Wrap HTML in multipart/alternative (required by Gmail for CID images)
    alt_part = MIMEMultipart("alternative")
    # Plain-text fallback (strip tags roughly)
    plain = re.sub(r'<[^>]+>', '', html)
    plain = re.sub(r'\n{3,}', '\n\n', plain).strip()
    alt_part.attach(MIMEText(plain[:5000], "plain", "utf-8"))
    alt_part.attach(MIMEText(html, "html", "utf-8"))
    msg.attach(alt_part)

    # Inline chart images
    for chart_path in chart_paths:
        path = Path(chart_path)
        if not path.exists():
            continue

        cid = chart_cid_map.get(str(path))
        if not cid:
            continue

        mime_type, _ = mimetypes.guess_type(str(path))
        if not mime_type or not mime_type.startswith("image/"):
            mime_type = "image/png"

        with open(path, "rb") as f:
            img = MIMEImage(f.read(), _subtype=mime_type.split("/")[1])

        img.add_header("Content-ID", f"<{cid}>")
        img.add_header("Content-Disposition", "inline", filename=path.name)
        msg.attach(img)

    return msg


# ── Gmail API helpers ────────────────────────────────────────────────────────

def _get_gmail_service(
    credentials_path: Path = CREDENTIALS_PATH,
    token_path: Path = TOKEN_PATH,
):
    """Authenticate and return Gmail API service object."""
    from google.auth.transport.requests import Request
    from google.oauth2.credentials import Credentials
    from google_auth_oauthlib.flow import InstalledAppFlow
    from googleapiclient.discovery import build

    creds = None
    if token_path.exists():
        creds = Credentials.from_authorized_user_file(str(token_path), SCOPES)

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            try:
                creds.refresh(Request())
            except Exception as e:
                log.error("gmail_token_refresh_failed", error=str(e))
                # Delete stale token so next interactive run re-authenticates
                token_path.unlink(missing_ok=True)
                raise RuntimeError(
                    f"Gmail token refresh failed: {e}\n"
                    "token.json has been deleted. Re-run manually to re-authenticate:\n"
                    "  uv run python scripts/send_report.py --date YYYY-MM-DD"
                ) from e
        else:
            if not credentials_path.exists():
                raise FileNotFoundError(
                    f"Gmail credentials not found at {credentials_path}.\n"
                    "Download OAuth 2.0 Client ID JSON from Google Cloud Console → APIs → Credentials.\n"
                    "Save as credentials.json in project root."
                )
            flow = InstalledAppFlow.from_client_secrets_file(str(credentials_path), SCOPES)
            print("\n=== Gmail OAuth 认证 ===")
            print("请在浏览器中打开下方链接完成授权（授权后页面会自动关闭）：\n")
            creds = flow.run_local_server(port=0, open_browser=False)

        token_path.write_text(creds.to_json())
        log.info("gmail_token_saved", path=str(token_path))

    return build("gmail", "v1", credentials=creds)


def _encode_message(msg: MIMEMultipart) -> dict:
    """Encode MIME message for Gmail API."""
    raw = base64.urlsafe_b64encode(msg.as_bytes()).decode("utf-8")
    return {"raw": raw}


# ── Public API ───────────────────────────────────────────────────────────────

def prepare_email(
    report_path: Path | str,
    chart_paths: list[Path] | None = None,
    to: str = "",
    subject: str = "",
    bcc: list[str] | None = None,
) -> tuple[MIMEMultipart, dict[str, str]]:
    """
    Prepare email message from a markdown report file + chart images.
    Returns (MIME message, cid_map).
    """
    report_path = Path(report_path)
    md_text = report_path.read_text(encoding="utf-8")
    chart_paths = chart_paths or []

    # Build CID map: path_str → content_id
    chart_cid_map: dict[str, str] = {}
    for i, cp in enumerate(chart_paths):
        cid = f"chart_{i}_{Path(cp).stem}"
        chart_cid_map[str(cp)] = cid

    # Convert markdown → HTML with embedded CID references + appended charts
    html = _md_to_html(md_text, chart_cid_map, chart_paths)

    # Build MIME message
    msg = build_email_message(to, subject, html, chart_paths, chart_cid_map, bcc=bcc)

    return msg, chart_cid_map


def send_report_email(
    report_path: Path | str,
    chart_paths: list[Path] | None = None,
    to: str | None = None,
    subject: str = "",
    bcc: list[str] | None = None,
    credentials_path: Path = CREDENTIALS_PATH,
    token_path: Path = TOKEN_PATH,
    config_path: str = "config.yaml",
) -> list[str]:
    """
    Send a markdown report as a styled HTML email with inline charts.
    Recipients are read from config.yaml by default. Returns list of message IDs.
    """
    if to:
        recipients = [to]
    else:
        recipients = load_recipients(config_path)
        log.info("recipients_from_config", count=len(recipients), addresses=recipients)

    import socket
    service = _get_gmail_service(credentials_path, token_path)
    msg_ids = []

    # Set socket-level timeout to prevent indefinite hangs on Gmail API calls
    old_timeout = socket.getdefaulttimeout()
    socket.setdefaulttimeout(60)  # 60s per API call
    try:
        for recipient in recipients:
            msg, _ = prepare_email(report_path, chart_paths, recipient, subject, bcc=bcc)
            result = service.users().messages().send(
                userId="me", body=_encode_message(msg)
            ).execute()
            msg_id = result.get("id", "")
            msg_ids.append(msg_id)
            log.info("gmail_sent", to=recipient, message_id=msg_id)
    finally:
        socket.setdefaulttimeout(old_timeout)

    log.info("gmail_send_complete", total=len(msg_ids))
    return msg_ids


def create_report_draft(
    report_path: Path | str,
    chart_paths: list[Path] | None = None,
    to: str = "",
    subject: str = "",
    bcc: list[str] | None = None,
    credentials_path: Path = CREDENTIALS_PATH,
    token_path: Path = TOKEN_PATH,
) -> str:
    """
    Create a Gmail draft with the report as styled HTML + inline charts.
    Returns the draft ID.
    """
    import socket
    msg, _ = prepare_email(report_path, chart_paths, to, subject, bcc=bcc)

    service = _get_gmail_service(credentials_path, token_path)
    old_timeout = socket.getdefaulttimeout()
    socket.setdefaulttimeout(60)
    try:
        result = service.users().drafts().create(
            userId="me", body={"message": _encode_message(msg)}
        ).execute()
    finally:
        socket.setdefaulttimeout(old_timeout)

    draft_id = result.get("id", "")
    log.info("gmail_draft_created", to=to, bcc_count=len(bcc or []), draft_id=draft_id)
    return draft_id


def send_alert_email(
    to: str,
    subject: str,
    body: str,
    credentials_path: Path = CREDENTIALS_PATH,
    token_path: Path = TOKEN_PATH,
) -> str:
    """Send a plain-text alert email (for pipeline failure notifications)."""
    import socket

    msg = MIMEText(body, "plain", "utf-8")
    msg["To"] = to
    msg["Subject"] = subject

    service = _get_gmail_service(credentials_path, token_path)
    old_timeout = socket.getdefaulttimeout()
    socket.setdefaulttimeout(30)
    try:
        result = service.users().messages().send(
            userId="me", body=_encode_message(msg)
        ).execute()
    finally:
        socket.setdefaulttimeout(old_timeout)

    msg_id = result.get("id", "")
    log.info("gmail_alert_sent", to=to, subject=subject, message_id=msg_id)
    return msg_id
