"""Render dividend dip screen, universe summary, and data coverage."""
from __future__ import annotations

from typing import Any

from ._render_fmt import _fmt_pct, _fmt_val

_DASH = "\u2014"


def render_dividend_screen(bundle: dict) -> list[str]:
    """Return lines for the dividend yield dip screen section."""
    dip_screen = bundle.get("dividend_dip_screen", {})
    dip_items = dip_screen.get("items", [])
    dip_summary = dip_screen.get("summary", {})
    if not dip_items:
        return []

    label_counts = dip_summary.get("label_counts", {})
    lines: list[str] = [
        "## Dividend Yield Dip Screen",
        "",
        "S&P 500 stocks whose current dividend yield is historically elevated "
        "(price cheap relative to own dividend history). "
        "DYP = percentile rank of current TTM yield vs own 5-year history.",
        "",
        f"**Candidates:** {dip_summary.get('rendered_count', len(dip_items))} passed DYP gate | "
        + " | ".join(f"{v} {k}" for k, v in label_counts.items()),
        "",
        "| Symbol | Label | Composite | DYP | Yield % | TS | SS | Price | RSI | 52W DD | Flags |",
        "|--------|-------|-----------|-----|---------|----|----|-------|-----|--------|-------|",
    ]
    for it in dip_items:
        flags_str = ", ".join(it.get("flags", [])) if it.get("flags") else _DASH
        label = it.get("label", _DASH)
        lines.append(
            f"| {it['symbol']} "
            f"| {label} "
            f"| {_fmt_val(it.get('composite_score'), 1)} "
            f"| {_fmt_val(it.get('dyp'), 1)} "
            f"| {_fmt_val(it.get('current_yield_pct'), 2)}% "
            f"| {_fmt_val(it.get('technical_score'), 1)} "
            f"| {_fmt_val(it.get('safety_score'), 1)} "
            f"| ${_fmt_val(it.get('current_price'), 2)} "
            f"| {_fmt_val(it.get('rsi14'), 1)} "
            f"| {_fmt_pct(it.get('drawdown_52w_pct'))} "
            f"| {flags_str} |"
        )
    lines += [
        "",
        "*DYP \u2265 70 = price cheaper than 70% of own history. "
        "TS = technical dip confirmation. SS = dividend safety.*",
        "*STRONG_DIP requires composite \u2265 70, DYP \u2265 80, and no red safety flags.*",
        "",
        "---",
        "",
    ]
    return lines


def render_universe_summary(bundle: dict) -> list[str]:
    """Return lines for the universe summary table."""
    lines: list[str] = [
        "## Universe Summary (all symbols)",
        "",
        "Brief snapshot of every scanned symbol \u2014 for cross-asset context only.",
        "",
        "| Symbol | Ret 1D | Regime | Z-Score | Strength |",
        "|--------|--------|--------|---------|----------|",
    ]
    for sym, data in sorted(bundle.get("universe_summary", {}).items()):
        regime = data.get("regime", _DASH)
        strength = data.get("strength", _DASH)
        lines.append(
            f"| {sym} | {_fmt_pct(data.get('ret_1d_pct'))} | "
            f"{regime} | "
            f"{_fmt_val(data.get('z_score'), 2)} | "
            f"{strength} |"
        )
    lines += ["", "---", ""]
    return lines


def render_coverage(bundle: dict) -> list[str]:
    """Return lines for the data coverage section."""
    cov = bundle.get("coverage", {})
    return [
        "## Data Coverage",
        "",
        f"- Symbols with price data: {cov.get('symbols_with_price_data', '?')}",
        f"- Notable items with news: {cov.get('notable_items_with_news', '?')}",
        f"- Notable items with SEC filings: {cov.get('notable_items_with_filings', '?')}",
        f"- Polymarket events tracked: {cov.get('polymarket_events_tracked', '?')}",
        "",
        "---",
        "",
        "*Payload generated by quant-research-v1. Feed this file to your agent of choice.*",
    ]
