#!/usr/bin/env python3
"""Render root-only crontab entries from ops/tasks.yaml."""
from __future__ import annotations

import argparse
from pathlib import Path

from tasklib import STACK_ROOT, load_registry, tasks


HEADER = """HOME=/home/ivena
# Quant Stack unified task schedule.
# Generated from ops/tasks.yaml. Do not edit this file by hand.
# Install only after dry-run review:
#   crontab ops/crontab.quant-stack
PATH=/home/ivena/miniconda3/bin:/home/ivena/.local/bin:/home/ivena/.nvm/versions/node/v20.19.5/bin:/home/ivena/.cargo/bin:/usr/local/bin:/usr/bin:/bin
QUANT_STACK_ROOT=/home/ivena/coding/quant-stack
"""


GROUP_LABELS = {
    "us": "US Pipeline",
    "cn": "CN Pipeline",
    "weekly": "Weekly Reports",
    "factor": "Factor Lab Daily",
    "paper": "Paper Trading",
    "maintenance": "Weekly Maintenance",
    "watchdog": "Watchdog",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render crontab from ops/tasks.yaml")
    parser.add_argument("--output", type=Path, help="Write rendered crontab to this path")
    return parser.parse_args()


def task_schedules(task: dict[str, object]) -> list[str]:
    if "schedules" in task and task["schedules"]:
        return list(task["schedules"])  # type: ignore[arg-type]
    schedule = task.get("schedule")
    return [str(schedule)] if schedule else []


def render() -> str:
    data = load_registry()
    lines: list[str] = [HEADER.rstrip(), ""]
    current_group = None
    for task_id, task in tasks(data).items():
        group = str(task.get("group") or "misc")
        if group != current_group:
            current_group = group
            label = GROUP_LABELS.get(group, group.title())
            lines.extend(["", f"# -- {label} --"])
        for schedule in task_schedules(task):
            lines.append(f"{schedule} cd $QUANT_STACK_ROOT && ops/run_task.sh {task_id}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    text = render()
    if args.output:
        path = args.output if args.output.is_absolute() else STACK_ROOT / args.output
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    else:
        print(text, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
