#!/usr/bin/env python3
"""Render root-only crontab entries from ops/tasks.yaml."""
from __future__ import annotations

import argparse
import os
from pathlib import Path

from tasklib import STACK_ROOT, load_registry, tasks


def _header() -> str:
    """Machine-agnostic crontab header derived from the environment.

    cron uses a minimal PATH, so `python3` must resolve to the project venv
    (which carries duckdb/tushare/analytics deps). Default PATH puts the
    quant-research-v1 venv first; override entirely with $QUANT_CRON_PATH.
    No host-specific paths are hard-coded (deploys on WSL or Oracle alike).
    """
    home = os.environ.get("HOME") or str(Path.home())
    root = str(STACK_ROOT)
    default_path = (
        f"{root}/quant-research-v1/.venv/bin:"
        f"{home}/.local/bin:{home}/.cargo/bin:/usr/local/bin:/usr/bin:/bin"
    )
    cron_path = os.environ.get("QUANT_CRON_PATH") or default_path
    return (
        f"HOME={home}\n"
        "# Quant Stack unified task schedule.\n"
        "# Generated from ops/tasks.yaml. Do not edit this file by hand.\n"
        "# Install only after dry-run review:\n"
        "#   crontab ops/crontab.quant-stack\n"
        f"PATH={cron_path}\n"
        f"QUANT_STACK_ROOT={root}\n"
    )


GROUP_LABELS = {
    "us": "US Pipeline",
    "cn": "CN Pipeline",
    "daily": "Cross-Market Daily",
    "weekly": "Weekly Reports",
    "factor": "Factor Lab Daily",
    "paper": "Paper Trading",
    "maintenance": "Weekly Maintenance",
    "watchdog": "Watchdog",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render crontab from ops/tasks.yaml")
    parser.add_argument("--output", type=Path, help="Write rendered crontab to this path")
    return parser.parse_args()


def task_schedules(task: dict[str, object]) -> list[str]:
    if "schedules" in task and task["schedules"]:
        return list(task["schedules"])  # type: ignore[arg-type]
    schedule = task.get("schedule")
    return [str(schedule)] if schedule else []


def render() -> str:
    data = load_registry()
    lines: list[str] = [_header().rstrip(), ""]
    current_group = None
    for task_id, task in tasks(data).items():
        schedules = task_schedules(task)
        if not schedules:
            continue
        group = str(task.get("group") or "misc")
        if group != current_group:
            current_group = group
            label = GROUP_LABELS.get(group, group.title())
            lines.extend(["", f"# -- {label} --"])
        for schedule in schedules:
            lines.append(f"{schedule} cd $QUANT_STACK_ROOT && ops/run_task.sh {task_id}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    text = render()
    if args.output:
        path = args.output if args.output.is_absolute() else STACK_ROOT / args.output
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    else:
        print(text, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
